locale: "en-US"
title: "Sirui Wang"
name: "Sirui Wang"
description: "PhD student at TUM | Generative AI, Remote Sensing"

url: "https://SiruiWang0731.github.io"
baseurl: ""

repository: "SiruiWang0731/SiruiWang0731.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

author:
  avatar: "profile.png"
  name: "Sirui Wang"
  bio: "PhD student at Technical University of Munich working on Generative AI for high-dimensional geospatial data."
  location: "Munich, Germany"
  email: "sirui.wang@tum.de"

  googlescholar: "https://scholar.google.com/citations?user=hnTcdloAAAAJ"
  github: "SiruiWang0731"
  linkedin: "sirui-wang-3b6924235"

# Publication categories
publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Collections
collections:
  publications:
    output: true
  talks:
    output: true
  portfolio:
    output: true
  teaching:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge
theme: null
